### ISSUE TITLE
Update the default text when there are no records found.

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.UI#112]
I can see how it can be a bit misleading when you are on a filtered view and the searchbox isn't populated (date range may be populated) and now there is no data and it says no stacks were found with the current filter.

> It seems it is simply a matter of me forgetting what the Dashboard looks like when there is nothing to report and the words ‘No stacks were found with the current filter.’ were a bit off-putting.

@ejsmith I can see the confusing when the filter box isn't populated, but the date range box is, but to an end user they just don't know.

**Comment by brutaldev** [comment]
Another reason it's confusing to people is because when the page refreshes all the menu items are collapsed and you can't see which menu option is selected (which is a filter in itself).

For example, when you load up the page https://be.exceptionless.io/organization/XYZ/error/recent, you don't see the "Most Recent" item selected under "Exceptions" so unless you look at the URL you have no idea what "filter" it's talking about. For some reason the default for me is https://be.exceptionless.io/organization/XYZ/logs/recent which never has data when I often assume I'm looking at the error dashboard.

Without the menu being expanded, there is no indication of which filter being applied.

**Comment by niemyjski** [comment]
I agree, and that's something we are working to fix via: https://github.com/exceptionless/Exceptionless.UI/issues/114

**Comment by brutaldev** [comment]
Perhaps then just change the wording if the "filter" text box is empty to "No data found with your current selection", if there is text in the filter, the existing message makes more sense as "No data found with your current filter of X". I think a large part of the confusion is that menu options are filters and so is the filter and the drop downs...

**Comment by niemyjski** [comment]
We've updated this behavior a bit but I'm not happy to the point of closing this issue.
