### ISSUE TITLE
As user I want to delete all exceptions from "Most Recent" section

### ISSUE THREAD

**Issue by Naggorny** [exceptionless/Exceptionless.UI#31]
- When user clicks on button "Clear all", all exceptions should be erased 
![2015-04-27_163424](https://cloud.githubusercontent.com/assets/11498834/7348620/b64592ca-ecfb-11e4-82c5-0eed5a5ad92b.jpg)

**Comment by niemyjski** [comment]
You can do this by clicking the top checkbox under most recent to select all items and then under bulk actions you can click the delete item.

**Comment by niemyjski** [comment]
Were you able to get this to work as expected?

**Comment by Naggorny** [comment]
Yes,I do it right now but:
- if you have more then 10 exceptions and check "select all", only 10 exceptions will be deleted ( that you see on current page), after it you should do the same actions.
- if you use "balk action" button, you should again and again confirm you actions ( it is too long and too many extra actions)

I want - one button and one action, delete all)

**Comment by niemyjski** [comment]
So you want to delete all events in a project?

**Comment by Naggorny** [comment]
Yes, only one click -> one action

**Comment by niemyjski** [comment]
I'm going to mark this as won't fix, because we think that this isn't a standard action you'd take on a small list of data. If more users ask for it we'll reopen this and add this feature. Currently you can do this with one click on the Manage Project page:

![image](https://cloud.githubusercontent.com/assets/1020579/7369174/1fd969cc-ed75-11e4-8e61-9ed0c431998b.png)

Out of personal curiosity, why are you trying to delete all events on a regular basis? It doesn't remove the events from your plan limit as those events were still processed, you can also hide events, and we have time filters that will only show you the last couple of days.

**Comment by Naggorny** [comment]
Example: we have loads of exceptions during 1 hour (filter on 4 projects is used), than we build new version with some fixes, than I recheck fixes, so I need to see only current exceptions in order to match them to new build

**Comment by niemyjski** [comment]
If you mark them as fixed, then push the build, it will mark the stack as regressed and you'll get a notification. Then you can still see the recent and old exceptions and by default they will be filtered out of your view.

**Comment by niemyjski** [comment]
Does this work for you?

**Comment by Naggorny** [comment]
No, this steps are not appropriate in my situation), ok, I will use "bulk action">delete>delete events.
Thank you for help.

**Comment by niemyjski** [comment]
If you are deleting all events under most recent, than that would be the same thing as resetting project data. Is there something that doesn't work with mark fixed? We want everyone to be happy but also make smart design decisions and involve the community.

**Comment by ejsmith** [comment]
You can also use the date range filter to view everything after you deployed the new version. In the future, we want to let you specify a version range to view and also be able to show only events from the latest version.

**Comment by Naggorny** [comment]
TO ejsmith:
- You are right, it works, thank you

**Comment by mpawelski** [comment]
In my case I wanted to delete all logs with log level less than "Warn". We had been running self hosted exceptionless for couple of months with very extensive logging from "Debug" level and higher but turns out it's not that useful for us. 
We now configured exceptionless client to just send "Warn" logs and higher but it would be good to have and an easy way to remove those millions of logs in Web UI.

I expected to have something like Gmail behaviour. When you click "top" checkbox on mails page it selects all mails in page, but show additional message that "you selected all mails on page (number of mails on page) click here to select all mails from search criteria (number of mails)". I'm not sure what's the actual English message, I use different language.

Similar behaviour would be great UX in exceptionless. You could easily filter and narrow search results of items you are interested in and perform bulk operations of all of them, not just on those in the first page.

**Comment by niemyjski** [comment]
> In my case I wanted to delete all logs with log level less than "Warn". We had been running self hosted exceptionless for couple of months with very extensive logging from "Debug" level and higher but turns out it's not that useful for us.
> We now configured exceptionless client to just send "Warn" logs and higher but it would be good to have and an easy way to remove those millions of logs in Web UI.
> 
> I expected to have something like Gmail behaviour. When you click "top" checkbox on mails page it selects all mails in page, but show additional message that "you selected all mails on page (number of mails on page) click here to select all mails from search criteria (number of mails)". I'm not sure what's the actual English message, I use different language.
> 
> Similar behaviour would be great UX in exceptionless. You could easily filter and narrow search results of items you are interested in and perform bulk operations of all of them, not just on those in the first page.

You'd currently need to apply a search filter and bulk delete form the Events grid. Have you considered adjusting your retention settings so they just roll off?

**Comment by mpawelski** [comment]
>You'd currently need to apply a search filter and bulk delete form the Events grid.
@niemyjski But this "bulk delete" only deletes events from current page. When I filer to "level:Debug" and click "bulk delete" then it only deletes the first page (15 elements, two DELETE api calls (one for 10 items second, for 5 items.) I use Exceptionless v7.0.5.

Anyway I had 2 millions logs, but most of them were grouped in stacks on just a couple of pages, so I was able to delete them all.
Still it would be great if there was an option for bulk deleting all events for given filter.
